events { worker_connections 1024; }
http {
    upstream odoo_backend { server odoo:8069; }
    upstream moodle_backend { server moodle:80; }
    server {
        listen 80;
        location / {
            proxy_pass http://odoo_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 720s;
            client_max_body_size 50m;
        }
        location /moodle/ {
            proxy_pass http://moodle_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            client_max_body_size 50m;
        }
    }
}
