apiVersion: batch/v1
kind: CronJob
metadata:
  name: moodle-cron
  namespace: production
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: moodle-cron-sa
          containers:
            - name: moodle-cron
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  POD=$(kubectl get pod -n production -l app=moodle -o jsonpath='{.items[0].metadata.name}')
                  kubectl exec -n production $POD -- php /var/www/html/admin/cli/cron.php
